# Generated by Django 6.0 on 2025-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Torta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='tortas/', verbose_name='Foto')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio (Opcional)')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Torta',
                'verbose_name_plural': 'Tortas',
            },
        ),
    ]
